public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 2");
        dog += 4;
        cat += 4;
        paper += 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 3");
        dog -= 3.5;
        cat -= 1.6;
        paper -= 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend += 2;
        System.out.println(friend);
        friend /= 7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog *= 10;
        System.out.println(frog);
        frog /= 3.5;
        System.out.println(frog);
        frog += 4;
        System.out.println(frog);
        System.out.println("Задача 6");
        var weight1 = 78.2;
        var weight2 = 82.7;
        var totalWeight = weight1 + weight2;
        var differenceInWeight = weight2 - weight1;
        System.out.println(totalWeight);
        System.out.println(differenceInWeight);
        System.out.println("Задача 7");
        var remainderOfDivision = weight2 % weight1;
        System.out.println(remainderOfDivision);
        System.out.println("Задача 8");
        var totalHours = 640;
        var hoursPerWorker = 8;
        var workers = totalHours / hoursPerWorker;
        System.out.println("Всего в компании работает " + workers + " человек");
        workers += 94;
        totalHours = workers * hoursPerWorker;
        System.out.println("Если в компании работает " + workers + " человека, то всего " + totalHours +
                " часа работы может быть поделено между сотрудниками");
    }
}